#### NDArray:
- Homogeneous elements (same datatype)

In [22]:
import numpy as np
import time

In [23]:
startPython = int(round(time.time() * 1000))

# Creates a list c by adding the elements of a and b

a1 = list(range(10000000))
b1 = list(range(10000000))

c = []

#This code can take up to 5 seconds to run depending on the type of machine you're using

for i in range(len(a1)):
    c.append(a1[i] + b1[i])
    
stopPython = int(round(time.time() * 1000))

# Below code does exactly the same thing but with Numpy Arrays

startNumpy = int(round(time.time() * 1000))

a2 = np.arange(10000000, dtype=int)
b2 = np.arange(10000000, dtype=int) # The Numpy code by comparison is shorter, doesn’t need a loop and it is almost instantaneous by comparison
c2 = a2 + b2

stopNumPy = int(round(time.time() * 1000))


# Here we express the time take by NumPy as a frac tion of the time taken by Python to perform the same operation

print ((stopPython-startPython)/(stopNumPy-startNumpy))

34.02564102564103


In [2]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]], dtype=np.float32)
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]], dtype=float32)

In [3]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]], dtype=float32)

In [4]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]], dtype=float32)

In [5]:
data.shape

(2, 3)

In [6]:
# dimension
data.ndim

2

In [7]:
data.dtype

dtype('float32')

In [8]:
# Creating prefilled array
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# Pass tuple to create higher dimension arrays
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.empty((2, 5, 3))

array([[[1.43994366e-311, 1.43993588e-311, 0.00000000e+000],
        [0.00000000e+000, 9.34609110e-307, 5.02034658e+175],
        [1.56138443e+161, 1.20075663e-071, 9.41412676e-067],
        [9.91646024e+164, 7.55637215e-067, 1.04914965e-153],
        [6.32299154e+233, 2.87505047e+161, 1.70098498e+256]],

       [[5.49109388e-143, 1.06396443e+224, 3.96041428e+246],
        [1.16318408e-028, 1.87868892e+160, 2.31855006e-056],
        [2.31739016e-052, 4.71188328e-062, 2.24151504e+174],
        [3.36163259e-067, 8.26218867e-072, 2.42240810e-028],
        [4.27632852e-033, 5.74015544e+180, 1.94919988e-153]]])

##### Arithmetic:

In [11]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [12]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [13]:
arr > arr2

array([[ True, False,  True],
       [False,  True, False]])

##### Indexing and Slicing

In [14]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr1[5:8] = 12
arr1

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [16]:
arr2 = arr1[5:8]
arr2

array([12, 12, 12])

In [19]:
arr2[:] = 25
arr2

array([25, 25, 25])

In [21]:
# numpy does not make a copy of the data
arr1

array([ 0,  1,  2,  3,  4, 25, 25, 25,  8,  9])

In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]], float)
arr[0,2] = 2.5
print(arr)
arr[0] = 7.5
print(arr)

[[1.  2.  2.5]
 [4.  5.  6. ]]
[[7.5 7.5 7.5]
 [4.  5.  6. ]]


In [30]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]], float)

print ("first", arr[0:1, 0:4] )

print ("second", arr[0:2, 0:4:2]) 

print ("third", arr[:, 0:2])

print ("fourth", arr[:, [0,3]])

first [[1. 2. 3. 4.]]
second [[1. 3.]
 [5. 7.]]
third [[ 1.  2.]
 [ 5.  6.]
 [ 9. 10.]]
fourth [[ 1.  4.]
 [ 5.  8.]
 [ 9. 12.]]


In [36]:
arr = np.arange(50)
arr = np.resize(arr, (10, 5))
print(arr)

np.savetxt("nums.txt", arr, fmt="%d", delimiter=",")

data = np.genfromtxt("nums.txt", delimiter=",")
print(data)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34.]
 [35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44.]
 [45. 46. 47. 48. 49.]]


##### Appending to ndarray