### Scalars (Rank 0 Tensors/0D Tensors)

In [1]:
x = 25
x

25

In [2]:
type(x)

int

##### Scalar tensors in PyTorch:

In [1]:
import torch

In [5]:
x_pt = torch.tensor(25)
x_pt

tensor(25)

In [6]:
y_pt = torch.tensor(25, dtype=float)
y_pt

tensor(25., dtype=torch.float64)

In [7]:
x_pt.shape

torch.Size([])

##### Scalar Tensors in Tensorflow

In [12]:
import tensorflow as tf

In [14]:
x_tf = tf.Variable(25)
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=25>

In [15]:
x_tf.shape

TensorShape([])

In [18]:
y_tf = tf.Variable(3)
# The python add operator is overloaded by tf.add() anyway
y_tf + x_tf

<tf.Tensor: shape=(), dtype=int32, numpy=28>

In [19]:
tf_sum = tf.add(x_tf, y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int32, numpy=28>

In [22]:
tf_sum.numpy()

np.int32(28)

## Vectors (1D tensors)
- Represents a point in space
- Vector of length 2 represents point in 2d space, length 3 in 3d space and so on
- [x1, x2] = [12, 4]

##### Vectors (Rank 1 tennsors) in numpy:

In [2]:
import numpy as np

In [3]:
x_v = np.array([12, 2, 5])
x_v

array([12,  2,  5])

In [4]:
x_v.shape

(3,)

##### Vector Transposition:

In [5]:
x_vt = x_v.T
x_vt

array([12,  2,  5])

In [6]:
y_v = np.array([[12, 2, 5]])
y_v

array([[12,  2,  5]])

In [7]:
y_v.shape

(1, 3)

In [8]:
y_vt = y_v.T
y_vt

array([[12],
       [ 2],
       [ 5]])

In [9]:
y_vt.shape

(3, 1)

##### Zero Vectors:
- Has no effect when added to another vector

In [10]:
z = np.zeros(3)
z

array([0., 0., 0.])

##### Vectors in Pytorch and Tensorflow:

In [11]:
x_vpt = torch.tensor([12, 4, 6])
x_vpt

tensor([12,  4,  6])

In [13]:
x_vtf = tf.Variable([12, 4, 6])
x_vtf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([12,  4,  6], dtype=int32)>